// frontend/components/Footer.vue
<template>
	<p>Copyright &copy; {{ start }}-{{ end }} - Timothy Cole - All Rights Reserved. &mdash; <a href="https://github.com/TimothyCole/timcole.me" target="_blank">{{ odds ? "Fork" : "Star" }} on Github</a></p>
</template>

<script>
export default {
	name: "Footer",
	data () {
		return {
			start: "1997",
			odds: Math.random() < 0.5,
			end: (new Date()).getFullYear()
		}
	}
}
</script>

<style lang="scss" scoped>
	p {
		color: #aabccb;
		font-size: 0.8em;
		display: inline-block;
		width: 100%;
		text-align: center;

		a {
			text-decoration: none;
			color: inherit;
		}
	}
</style>

// web/components/footer.tsx
import * as React from "react";

import "../styles/footer.scss";

class Footer extends React.Component {
	private start: String = "1997";
	private end: String = (new Date()).getFullYear().toString();
	private odds: Boolean = Math.random() < 0.5;

	render() {
		return (
			<p className="footer">Copyright &copy; {this.start}-{this.end} - Timothy Cole - All Rights Reserved. &mdash; <a href="https://github.com/TimothyCole/timcole.me" target="_blank">{ this.odds ? "Fork": "Star" } on Github</a></p>
		)
	}
};

export default Footer;
