// src/components/footer.tsx
import { FC } from 'react';

const Footer: FC = () => (
  <footer className="text-center text-gray-500 py-6">
    Copyright &copy; 1997-{new Date().getFullYear()} - Timothy Cole - All Rights
    Reserved. —{' '}
    <a
      href="https://github.com/timcole/timcole.me"
      target="_blank"
      className="border-b-2 border-dashed border-gray-600"
    >
      Star on GitHub
    </a>
  </footer>
);

export default Footer;

// src/components/Footer.vue
<template>
	<p>Copyright &copy; {{ start }}-{{ end }} - Timothy Cole - All Rights Reserved.</p>
</template>

<script>
export default {
	name: "Footer",
	data () {
		return {
			start: "1997",
			end: (new Date()).getFullYear()
		}
	}
}
</script>

<style lang="scss" scoped>
	p {
		color: #aabccb;
		font-size: 0.8em;
		display: inline-block;
		width: 100%;
		text-align: center;
	}
</style>
